export const banks = [
  { code: "0163", name: "BANCO DEL TESORO" },
  { code: "0172", name: "BANCAMIGA" },
  { code: "0171", name: "BANCO ACTIVO" },
  { code: "0166", name: "BANCO AGRICOLA DE VENEZUELA" },
  { code: "0128", name: "BANCO CARONI" },
  { code: "0102", name: "BANCO DE VENEZUELA" },
  { code: "0114", name: "BANCO DEL CARIBE" },
  { code: "0007", name: "BANCO DIGITAL DE LOS TRABAJADADORES" },
  { code: "0115", name: "BANCO EXTERIOR" },
  { code: "0105", name: "BANCO MERCANTIL" },
  { code: "0191", name: "BANCO NACIONAL DE CREDITO" },
  { code: "0116", name: "BANCO OCCIDENTAL DE DESCUENTO" },
  { code: "0138", name: "BANCO PLAZA" },
  { code: "0108", name: "BANCO PROVINCIAL" },
  { code: "0137", name: "BANCO SOFITASA" },
  { code: "0104", name: "BANCO VENEZOLANO DE CREDITO" },
  { code: "0168", name: "BANCRECER" },
  { code: "0134", name: "BANESCO BANCO UNIVERSAL" },
  { code: "0177", name: "BANFANB" },
  { code: "0174", name: "BANPLUS" },
  { code: "0157", name: "DEL SUR" },
  { code: "0151", name: "FONDO COMUN" },
  { code: "0169", name: "MI BANCO" },
  { code: "0178", name: "N58 BANCO DIGITAL" },
  { code: "0156", name: "100 % BANCO" },
];

export const paymentInformation = {
  bankName: "Banco del Tesoro",
  taxDocument: "J-502896872",
  phone: "0424-285-9949",
};
